apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-offer-decision-service
  labels:
    app: offer-decision-service
  annotations:
    {{- if .Values.prometheus.scrape }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.prometheus.port }}"
    prometheus.io/path: "{{ .Values.prometheus.path }}"
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: offer-decision-service
